#!/usr/bin/env bash
set -euo pipefail

OUT="book/API_CONTRACT.md"

{
  echo "# Book API Contract"
  echo
  echo "This file is generated from \`src/lib.rs\` and represents the public symbols the book should treat as current API."
  echo
  echo "## Public Modules"
  echo
  echo '```text'
  rg '^pub mod ' src/lib.rs | sed -E 's/^pub mod ([^;]+);/\1/' | sort
  echo '```'
  echo
  echo "## Public Re-Exports"
  echo
  echo '```text'
  rg '^pub use ' src/lib.rs | sed -E 's/^pub use //' | sed 's/;//' | sort
  echo '```'
  echo
  echo "## Layers Re-Exports"
  echo
  echo '```text'
  rg '^pub use ' src/layers/mod.rs | sed -E 's/^pub use //' | sed 's/;//' | sort
  echo '```'
  echo
  echo "## Performance Re-Exports"
  echo
  echo '```text'
  rg '^pub use ' src/performance/mod.rs | sed -E 's/^pub use //' | sed 's/;//' | sort
  echo '```'
  echo
  echo "Generated by: \`scripts/generate_book_api_contract.sh\`"
} > "${OUT}"

echo "Wrote ${OUT}"
